### ISSUE TITLE
there's no link to npm in the readme 😦

### ISSUE THREAD

**Issue by catdad** [stezu/eslint-config-stezu#1]

**Comment by stezu** [comment]
I'd hardly call it a readme...

**Comment by catdad** [comment]
Well... I still wanted to just click through but you made me type stuff.

**Comment by stezu** [comment]
Just for you!

<img width="340" alt="screen shot 2018-03-06 at 7 34 08 pm" src="https://user-images.githubusercontent.com/3180534/37072269-6193a404-2175-11e8-97ae-aa2f781375ee.png">

**Comment by catdad** [comment]
👍
